In [1]:
import numpy as np


In [9]:
b = np.empty(2,dtype=int)
print("Matrix b: \n",b)

Matrix b: 
 [0 0]


In [11]:
c = np.zeros([1,2],dtype=int)
print("The value of C is: \n",c)

The value of C is: 
 [[0 0]]


In [12]:
array1 = np.array([4,24,5,7])
array2 = np.array([89,56,5,2])

In [13]:
np.add(array1,array2)

array([93, 80, 10,  9])

In [15]:
np.subtract(array2,array1)

array([85, 32,  0, -5])

In [16]:
np.multiply(array1,array2)

array([ 356, 1344,   25,   14])

In [17]:
np.divide(array1,array2)

array([0.04494382, 0.42857143, 1.        , 3.5       ])

In [18]:
# CREATING A SEQUENCE OF INTEGERS FROM 10 TO 1 IN STEPS OF -2

In [19]:
array3 = np.arange(10,1,-2)

In [20]:
array3

array([10,  8,  6,  4,  2])

In [21]:
#Indexing the newly created array

In [22]:
array4 = array3[np.array([3,2,1])]

In [23]:
array4

array([4, 6, 8])

In [26]:
array3[np.array([3,2,1])]

array([4, 6, 8])

In [27]:
array_to_be_sliced = np.arange(20)

In [ ]:
# a[start:stop:step]
print("\n array_to_be_sliced[-8:17:1] = ",array_to_be_sliced[-8:17:1])